version = 1
SPDX-PackageName = "nebula"
SPDX-PackageSupplier = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-PackageDownloadLocation = "https://github.com/InditexTech/nebula"

[[annotations]]
path = [
    "*",
    "NOTICE",
    ".gitignore",
    ".github/CODEOWNERS",
    "**env.sample",
    "**uv.lock",
    "**/*json",
    "**/*txt",
    "**/*gitignore",
    "**/*Dockerfile",
    "**/*.pyc",
    "**/*.png",
    "**/*.mp4",
    "**/*.lottie",
    "**/*.svg",
    "**/*.conf",
    "**/*.webm",
    "**/*.ico",
    "**/*.webmanifest",
    "docs/diagrams/*.html",
    "**/mockServiceWorker.js",
]
SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"
