version = 1
SPDX-PackageName = "kumoss"
SPDX-PackageSupplier = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-PackageDownloadLocation = "https://github.com/InditexTech/kumoss"

[[annotations]]
path = [
    "*",
    "NOTICE",
    ".gitignore",
    ".github/CODEOWNERS",
    "**env.sample",
    "**uv.lock",
    "**/*json",
    "**/*txt",
    "**/*gitignore",
    "**/*Dockerfile",
    "**/*.pyc",
    "**/*.png",
    "**/*.jpg",
    "**/*.mp4",
    "**/*.lottie",
    "**/*.svg",
    "**/*.conf",
    "**/*.webm",
    "**/*.ico",
    "**/*.webmanifest",
    "**/mockServiceWorker.js",
]
SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
    "docs/**/*.adoc",
    "docs/**/*.yml",
    "docs/**/*.mjs",
    "docs/src/modules/*/attachments/*.html",
    "docs/.tool-versions",
    ".github/workflows/docouture-*.yml",
]
SPDX-FileCopyrightText = "2026 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)"
SPDX-License-Identifier = "Apache-2.0"
