server {
    listen 80;
    listen [::]:80;

    # Security Headers
    add_header X-Frame-Options            "SAMEORIGIN";
    add_header X-Content-Type-Options     "nosniff";

    client_max_body_size 4m;

    # API Proxy
    location /api {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 600;
        proxy_connect_timeout 600;
        proxy_send_timeout 600;

        proxy_pass http://core:8000;
    }

    # Phoenix Tracer
    location /monitoring/ {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 600;
        proxy_connect_timeout 600;
        proxy_send_timeout 600;

        proxy_pass http://phoenix:6006/;
    }

    # priority with ^~
    location ^~ /favicon/ {
        root /public;
        try_files $uri =404;
        expires 7d;
        access_log off;
    }

    location / {
        root /public/dist/;
        index index.html;
        try_files $uri $uri/ /index.html;
        expires 1d;
    }

    gzip on;
    gzip_http_version 1.1;
    gzip_types text/css application/javascript application/json text/javascript;
    gzip_min_length 1k;
    gzip_comp_level 6;

    # Logging
    access_log /dev/stdout combined;
    error_log /dev/stdout warn;
}

# object-storage rustfs
server {
   listen       9000;
   listen  [::]:9000;

   client_max_body_size 10m;
   proxy_buffering off;
   proxy_request_buffering off;

   location / {
      add_header Access-Control-Allow-Origin "*" always;

      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      # Disable Nginx from converting HEAD to GET
      proxy_cache_convert_head off;
      proxy_connect_timeout 300;

      # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
      proxy_http_version 1.1;
      chunked_transfer_encoding off;

      proxy_pass http://object-storage:9000;
   }
}

